<?php

include_once('dlr_groups.features.inc');

/**
 * Implementation of hook_context_links_alter().
 * 
 * Have only one context link button appear for dlr group nodes: Edit the node.
 * 
 */

function dlr_groups_context_links_alter(&$links) {
  if (context_get('context', 'dlr_groups_context_links')) {
    $links = array();
    $active_space = spaces_get_space();
    $item = menu_get_item('node/'.$active_space->id.'/edit');
    if ($item['access']) {
      $links['admin_groups'] = array('title' => t('Edit @type', array('@type' => $active_space->group->type)), 'href' => $item['href']);
    }
  }
}

/**
 * Implementation of hook_menu_alter().
 * 
 * Hide certain menu items that appear as tabs.
 * 
 */
function dlr_groups_menu_alter(&$items){
  $items['node/%/buildmodes'] = null;
  $items['node/%/features'] = null;
  $items['node/%/by_subject'] = null;
}
